/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import dao.HCDAO;
import dao.ImagenDAO;
import entidades.Imagen;
import entidades.Receta;
import java.awt.Desktop;
import java.io.File;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class HCDatosConsultas extends javax.swing.JPanel {

    /**
     * Creates new form HCDatosConsultas
     */
    public HCDatosConsultas() {
        initComponents();
        
        txtIdConsulta.setVisible(false);
        String textoLbl="<html><body>Exámenes<br>complementarios</body></html>";
        lblExamenesComp.setText(textoLbl);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane7 = new javax.swing.JScrollPane();
        tblConsultas = new javax.swing.JTable();
        lblConsulta = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtTratamiento = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtDiagnostico = new javax.swing.JTextField();
        txtFecha = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtTalla = new javax.swing.JTextField();
        txtPeso = new javax.swing.JTextField();
        txtIMC = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtTemperatura = new javax.swing.JTextField();
        txtPulso = new javax.swing.JTextField();
        txtPresionA = new javax.swing.JTextField();
        txtMotivo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtCuadroClinico = new javax.swing.JTextArea();
        lblExamenesComp = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtExamenesComp = new javax.swing.JTextArea();
        txtIdConsulta = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblReceta = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblImagenes = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(862, 860));

        tblConsultas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblConsultas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblConsultasMouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(tblConsultas);

        lblConsulta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblConsulta.setText("Última consulta");

        jLabel3.setText("Fecha:");

        txtTratamiento.setEditable(false);
        txtTratamiento.setColumns(20);
        txtTratamiento.setRows(5);
        txtTratamiento.setOpaque(false);
        jScrollPane3.setViewportView(txtTratamiento);

        jLabel13.setText("Tratamiento:");

        jLabel12.setText("Diagnóstico:");

        jLabel11.setText("Motivo:");

        jLabel16.setText("Receta");

        txtDiagnostico.setEditable(false);
        txtDiagnostico.setBorder(null);
        txtDiagnostico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiagnosticoActionPerformed(evt);
            }
        });

        txtFecha.setEditable(false);
        txtFecha.setBorder(null);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("Otras consultas");

        jLabel1.setText("Talla (cms):");

        jLabel2.setText("Peso (kgs):");

        jLabel4.setText("IMC:");

        txtTalla.setEditable(false);
        txtTalla.setBorder(null);

        txtPeso.setEditable(false);
        txtPeso.setBorder(null);
        txtPeso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesoActionPerformed(evt);
            }
        });

        txtIMC.setEditable(false);
        txtIMC.setBorder(null);

        jLabel5.setText("Temperatura (°C):");

        jLabel6.setText("Pulso:");

        jLabel7.setText("Presión arterial:");

        txtTemperatura.setEditable(false);
        txtTemperatura.setBorder(null);

        txtPulso.setEditable(false);
        txtPulso.setBorder(null);

        txtPresionA.setEditable(false);
        txtPresionA.setBorder(null);

        txtMotivo.setEditable(false);
        txtMotivo.setBorder(null);

        jLabel8.setText("Cuadro clínico");

        txtCuadroClinico.setEditable(false);
        txtCuadroClinico.setColumns(20);
        txtCuadroClinico.setRows(5);
        txtCuadroClinico.setOpaque(false);
        jScrollPane1.setViewportView(txtCuadroClinico);

        lblExamenesComp.setText("Exámenes");

        txtExamenesComp.setEditable(false);
        txtExamenesComp.setColumns(20);
        txtExamenesComp.setRows(5);
        txtExamenesComp.setOpaque(false);
        jScrollPane2.setViewportView(txtExamenesComp);

        txtIdConsulta.setEditable(false);

        tblReceta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblReceta.setOpaque(false);
        jScrollPane4.setViewportView(tblReceta);

        tblImagenes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblImagenes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblImagenesMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tblImagenes);

        jLabel9.setText("Imágenes");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel11)
                            .addGap(778, 778, 778))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(lblConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(txtIdConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel4)
                                                .addComponent(jLabel2)
                                                .addComponent(jLabel1))
                                            .addGap(43, 43, 43)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(txtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtIMC, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(txtTalla, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addGap(66, 66, 66)
                                            .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel7))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtPresionA, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txtPulso, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                                            .addComponent(txtTemperatura, javax.swing.GroupLayout.Alignment.LEADING)))
                                    .addGap(0, 0, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel12)
                                        .addComponent(lblExamenesComp, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel16)
                                        .addComponent(jLabel13)
                                        .addComponent(jLabel9))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtDiagnostico, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(0, 227, Short.MAX_VALUE))
                                        .addComponent(jScrollPane1)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(txtMotivo)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel14)
                                                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addComponent(jScrollPane2)
                                        .addComponent(jScrollPane3))))
                            .addGap(181, 181, 181)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblConsulta)
                            .addComponent(txtIdConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtTalla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(txtTemperatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(txtPulso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtIMC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(txtPresionA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txtMotivo, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblExamenesComp)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDiagnostico, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addContainerGap(91, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblConsultasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblConsultasMouseClicked
        // TODO add your handling code here:

        txtFecha.setText(String.valueOf(tblConsultas.getValueAt(tblConsultas.getSelectedRow(), 0)));
        txtTalla.setText(String.valueOf(tblConsultas.getValueAt(tblConsultas.getSelectedRow(), 1)));
        txtPeso.setText(String.valueOf(tblConsultas.getValueAt(tblConsultas.getSelectedRow(), 2)));
        txtIMC.setText(String.valueOf(tblConsultas.getValueAt(tblConsultas.getSelectedRow(), 3)));
        txtTemperatura.setText(String.valueOf(tblConsultas.getValueAt(tblConsultas.getSelectedRow(), 4)));
        txtPulso.setText(String.valueOf(tblConsultas.getValueAt(tblConsultas.getSelectedRow(), 5)));
        txtPresionA.setText(String.valueOf(tblConsultas.getValueAt(tblConsultas.getSelectedRow(), 6)));
        txtMotivo.setText(String.valueOf(tblConsultas.getValueAt(tblConsultas.getSelectedRow(), 7)));
        txtCuadroClinico.setText(String.valueOf(tblConsultas.getValueAt(tblConsultas.getSelectedRow(), 8)));
        txtExamenesComp.setText(String.valueOf(tblConsultas.getValueAt(tblConsultas.getSelectedRow(), 9)));
        txtDiagnostico.setText(String.valueOf(tblConsultas.getValueAt(tblConsultas.getSelectedRow(), 10)));
        txtTratamiento.setText(String.valueOf(tblConsultas.getValueAt(tblConsultas.getSelectedRow(), 11)));
        //txtReceta.setText(String.valueOf(tblConsultas.getValueAt(tblConsultas.getSelectedRow(), 4)));
        int idConsulta=Integer.parseInt(tblConsultas.getValueAt(tblConsultas.getSelectedRow(), 12).toString());
        txtIdConsulta.setText(tblConsultas.getValueAt(tblConsultas.getSelectedRow(), 12).toString());
        datosReceta(idConsulta);
        mostrarImagenes(idConsulta);
        
        if (tblConsultas.getSelectedRow() == 0) {
            lblConsulta.setText("Última consulta");
        } else {
            lblConsulta.setText("Consulta");
        }
    }//GEN-LAST:event_tblConsultasMouseClicked

    public void datosReceta(int idConsulta) {
        HCDAO hc = new HCDAO();

        try {
            ArrayList<Receta> receta = hc.datosReceta(idConsulta);

            DefaultTableModel modelo = new DefaultTableModel() {

                @Override
                public boolean isCellEditable(int row, int col) {
                    return false;
                }
            };

            modelo.addColumn("Medicamento");
            modelo.addColumn("Cantidad");
            

            for (Receta r : receta) {
                String[] fila = new String[2];
                fila[0] = r.getNombreMedicamento();
                fila[1] = String.valueOf(r.getCantidad());
                
                modelo.addRow(fila);
            }

            tblReceta.setModel(modelo);

            
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }

    }
    
    public void mostrarImagenes(int idConsulta) {
        HCDAO hc = new HCDAO();

        try {
            ArrayList<Imagen> imagenes = hc.imagenesConsulta(idConsulta);

            tblImagenes.setDefaultRenderer(Object.class, new btTablaImagenes());
            DefaultTableModel modelo = new DefaultTableModel() {

                @Override
                public boolean isCellEditable(int row, int col) {
                    return false;
                }
            };

            modelo.addColumn("Id");
            modelo.addColumn("Nombre");
            modelo.addColumn("Archivo");
            modelo.addColumn("Extensión");

            for (Imagen img : imagenes) {
                Object[] fila = new Object[4];
                fila[0] = img.getId();
                fila[1] = img.getNombre();
                if (img.getArchivo() != null) {
                    fila[2] = new JButton("Ver imagen");
                } else {
                    fila[2] = new JButton("vacio");
                }
                fila[3]= img.getExtension();

                modelo.addRow(fila);
            }

            tblImagenes.setModel(modelo);

            tblImagenes.getColumnModel().getColumn(0).setMaxWidth(0);
            tblImagenes.getColumnModel().getColumn(0).setMinWidth(0);
            tblImagenes.getTableHeader().getColumnModel().getColumn(0).setMaxWidth(0);
            tblImagenes.getTableHeader().getColumnModel().getColumn(0).setMinWidth(0);
            tblImagenes.getColumnModel().getColumn(3).setMaxWidth(0);
            tblImagenes.getColumnModel().getColumn(3).setMinWidth(0);
            tblImagenes.getTableHeader().getColumnModel().getColumn(3).setMaxWidth(0);
            tblImagenes.getTableHeader().getColumnModel().getColumn(3).setMinWidth(0);

        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }

    }
    
    private void txtDiagnosticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiagnosticoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiagnosticoActionPerformed

    private void txtPesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesoActionPerformed

    private void tblImagenesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblImagenesMouseClicked
        // TODO add your handling code here:
        int column=tblImagenes.getColumnModel().getColumnIndexAtX(evt.getX());
        int row= evt.getY() / tblImagenes.getRowHeight();
        if(row<tblImagenes.getRowCount() && row>=0 && column<tblImagenes.getColumnCount() && column>=0){
            int id=(int) tblImagenes.getValueAt(row, 0);
            String ext= String.valueOf(tblImagenes.getValueAt(row, 3));
            Object value=tblImagenes.getValueAt(row, column);
            if(value instanceof JButton){
                ((JButton) value).doClick();
                JButton boton=(JButton) value;
                if(boton.getText().equals("vacio")){
                    JOptionPane.showMessageDialog(null, "no hay archivo");
                }else{
                    ImagenDAO imgDAO= new ImagenDAO();
                    imgDAO.abrirImagen(id);
                    try{
                        Desktop.getDesktop().open(new File("new"+ext));
                    }catch(Exception e){
                        
                    }
                }
            }
        }
    }//GEN-LAST:event_tblImagenesMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JLabel lblConsulta;
    private javax.swing.JLabel lblExamenesComp;
    public static javax.swing.JTable tblConsultas;
    public static javax.swing.JTable tblImagenes;
    public static javax.swing.JTable tblReceta;
    public static javax.swing.JTextArea txtCuadroClinico;
    public static javax.swing.JTextField txtDiagnostico;
    public static javax.swing.JTextArea txtExamenesComp;
    public static javax.swing.JTextField txtFecha;
    public static javax.swing.JTextField txtIMC;
    public static javax.swing.JTextField txtIdConsulta;
    public static javax.swing.JTextField txtMotivo;
    public static javax.swing.JTextField txtPeso;
    public static javax.swing.JTextField txtPresionA;
    public static javax.swing.JTextField txtPulso;
    public static javax.swing.JTextField txtTalla;
    public static javax.swing.JTextField txtTemperatura;
    public static javax.swing.JTextArea txtTratamiento;
    // End of variables declaration//GEN-END:variables
}
