/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import java.awt.GridBagLayout;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.WindowConstants;

/**
 *
 * @author Usuario
 */
public class Menu extends javax.swing.JFrame {

    
    JFrame menu=this;
    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/img/hc_icon.png")).getImage());
        setExtendedState(MAXIMIZED_BOTH);
        lblLoading.setVisible(false);
        lblLoading.setOpaque(true);
        
    }
    
    public class _LoadListaPacientes implements Runnable {

        public void show() {
            new Thread(this).start();
        }

        public void run() {
            lblLoading.setVisible(true);
            //ListadoPacientes listado = new ListadoPacientes();
            ListadoPacientes2 listado = new ListadoPacientes2(menu,true);
            listado.setLocationRelativeTo(menu);
            lblLoading.setVisible(false);
            listado.setVisible(true);
            
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        content = new javax.swing.JPanel();
        panelButtons = new javax.swing.JPanel();
        btListaPacientes = new javax.swing.JButton();
        btNuevoPaciente = new javax.swing.JButton();
        btNuevaConsulta = new javax.swing.JButton();
        btHC = new javax.swing.JButton();
        btUltimasConsultas = new javax.swing.JButton();
        panelPortada = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblLoading = new javax.swing.JLabel();
        lblPortada = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Historial Clínico");

        content.setBackground(new java.awt.Color(255, 255, 255));
        content.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelButtons.setBackground(new java.awt.Color(47, 65, 112));
        panelButtons.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btListaPacientes.setBackground(new java.awt.Color(255, 255, 255));
        btListaPacientes.setText("Lista de \npacientes");
        btListaPacientes.setFocusPainted(false);
        btListaPacientes.setFocusable(false);
        btListaPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btListaPacientesActionPerformed(evt);
            }
        });
        panelButtons.add(btListaPacientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 160, 50));

        btNuevoPaciente.setBackground(new java.awt.Color(255, 255, 255));
        btNuevoPaciente.setText("Nuevo Paciente");
        btNuevoPaciente.setFocusPainted(false);
        btNuevoPaciente.setFocusable(false);
        btNuevoPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNuevoPacienteActionPerformed(evt);
            }
        });
        panelButtons.add(btNuevoPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 160, 50));

        btNuevaConsulta.setBackground(new java.awt.Color(255, 255, 255));
        btNuevaConsulta.setText("Nueva Consulta");
        btNuevaConsulta.setFocusPainted(false);
        btNuevaConsulta.setFocusable(false);
        btNuevaConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNuevaConsultaActionPerformed(evt);
            }
        });
        panelButtons.add(btNuevaConsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 160, 50));

        btHC.setBackground(new java.awt.Color(255, 255, 255));
        btHC.setText("Historial Clínico");
        btHC.setFocusable(false);
        btHC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHCActionPerformed(evt);
            }
        });
        panelButtons.add(btHC, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 160, 50));

        btUltimasConsultas.setBackground(new java.awt.Color(255, 255, 255));
        btUltimasConsultas.setText("Últimas Consultas");
        btUltimasConsultas.setFocusPainted(false);
        btUltimasConsultas.setFocusable(false);
        btUltimasConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUltimasConsultasActionPerformed(evt);
            }
        });
        panelButtons.add(btUltimasConsultas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 160, 50));

        content.add(panelButtons, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 760));

        panelPortada.setBackground(new java.awt.Color(255, 255, 255));
        panelPortada.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(47, 65, 112));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CLÍNICO");
        panelPortada.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 290, 360, 50));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(47, 65, 112));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("SISTEMA");
        panelPortada.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 170, 360, 50));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(47, 65, 112));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("DE HISTORIAL");
        panelPortada.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 230, 370, 50));

        lblLoading.setBackground(new java.awt.Color(255, 255, 255));
        lblLoading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLoading.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Double Ring-1s-200px.gif"))); // NOI18N
        lblLoading.setLabelFor(this);
        lblLoading.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelPortada.add(lblLoading, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 240, 284, 237));

        lblPortada.setForeground(new java.awt.Color(0, 0, 255));
        lblPortada.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPortada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/portada 2.jpg"))); // NOI18N
        panelPortada.add(lblPortada, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1130, 730));

        content.add(panelPortada, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 1130, 730));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(content, javax.swing.GroupLayout.PREFERRED_SIZE, 731, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btNuevaConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNuevaConsultaActionPerformed
        // TODO add your handling code here:
        /*
        NuevaConsulta2 n= new NuevaConsulta2(this,true);
        n.setLocationRelativeTo(this);
        n.setVisible(true);
        */
        new _LoadListaPacientesConsulta().show();
    }//GEN-LAST:event_btNuevaConsultaActionPerformed

    private void btNuevoPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNuevoPacienteActionPerformed
        // TODO add your handling code here:
        NuevoPaciente2 n= new NuevoPaciente2(this,true);
        n.setLocationRelativeTo(this);
        n.setVisible(true);

    }//GEN-LAST:event_btNuevoPacienteActionPerformed

    private void btListaPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btListaPacientesActionPerformed
        // TODO add your handling code here:
        new _LoadListaPacientes().show();
    }//GEN-LAST:event_btListaPacientesActionPerformed

    private void btHCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHCActionPerformed
        // TODO add your handling code here:
        
        new _LoadListaPacientesHC().show();
    }//GEN-LAST:event_btHCActionPerformed

    private void btUltimasConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUltimasConsultasActionPerformed
        // TODO add your handling code here:
        new _LoadListaConsultas().show();
    }//GEN-LAST:event_btUltimasConsultasActionPerformed

    public class _LoadListaPacientesHC implements Runnable {

        public void show() {
            new Thread(this).start();
        }

        public void run() {
            lblLoading.setVisible(true);
            BuscarPacienteC bp = new BuscarPacienteC(new javax.swing.JDialog(),true);
            bp.setLocationRelativeTo(menu);
            lblLoading.setVisible(false);
            //bp.setVisible(true);
            int idPaciente=bp.obtenerIdParaHC();
            HistorialClinico hc= new HistorialClinico(menu,true);
            hc.datosPersonales(idPaciente);
            hc.datosUltimaConsulta(idPaciente);
            hc.datosTodasConsultas(idPaciente);
            hc.setLocationRelativeTo(menu);
            hc.setVisible(true);
            
            
        }
    }
    
    public class _LoadListaPacientesConsulta implements Runnable {

        public void show() {
            new Thread(this).start();
        }

        public void run() {
            lblLoading.setVisible(true);
            NuevaConsulta2 nc = new NuevaConsulta2(menu,true);
            nc.setLocationRelativeTo(menu);
            lblLoading.setVisible(false);
            nc.setVisible(true);
            
        }
    }
    
       public class _LoadListaConsultas implements Runnable {

        public void show() {
            new Thread(this).start();
        }

        public void run() {
            lblLoading.setVisible(true);
            //ListadoPacientes listado = new ListadoPacientes();
            UltimasConsultas listado = new UltimasConsultas(menu,true);
            listado.setLocationRelativeTo(menu);
            lblLoading.setVisible(false);
            listado.setVisible(true);
            
            
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btHC;
    private javax.swing.JButton btListaPacientes;
    private javax.swing.JButton btNuevaConsulta;
    private javax.swing.JButton btNuevoPaciente;
    private javax.swing.JButton btUltimasConsultas;
    private javax.swing.JPanel content;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    public javax.swing.JLabel lblLoading;
    private javax.swing.JLabel lblPortada;
    private javax.swing.JPanel panelButtons;
    private javax.swing.JPanel panelPortada;
    // End of variables declaration//GEN-END:variables
}
