/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import java.awt.KeyboardFocusManager;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import javax.swing.AbstractAction;
import javax.swing.ActionMap;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author Usuario
 */
public class NCDatos2 extends javax.swing.JPanel {

    /**
     * Creates new form NuevaConsulta2
     */
    public NCDatos2() {
        initComponents();

        tblReceta.getColumnModel().getColumn(0).setPreferredWidth(500);
        tblReceta.getColumnModel().getColumn(1).setPreferredWidth(100);

        ActionMap am = tblReceta.getActionMap();
        //am.get("selectPreviousColumnCell").setEnabled(false);
        //am.get("selectNextColumnCell").setEnabled(false);
        //am.put("selectPreviousColumnCell", new PreviousFocusHandler());
        //am.put("selectNextColumnCell", new NextFocusHandler());

        //tblReceta.setDefaultEditor(Integer.class, new EditorTabla());
        //TableColumn col = tblReceta.getColumnModel().getColumn(1);
        //col.setCellEditor(new EditorTabla());
        DefaultTableModel modelo = new DefaultTableModel() {

            @Override
            public boolean isCellEditable(int row, int col) {
                return false;
            }
        };

        modelo.addColumn("Nombre");
        modelo.addColumn("Ruta");

        tblImagenes.setModel(modelo);

    }

    public class PreviousFocusHandler extends AbstractAction {

        public void actionPerformed(ActionEvent evt) {
            KeyboardFocusManager manager = KeyboardFocusManager.getCurrentKeyboardFocusManager();
            manager.focusPreviousComponent();
        }

    }

    public class NextFocusHandler extends AbstractAction {

        public void actionPerformed(ActionEvent evt) {
            KeyboardFocusManager manager = KeyboardFocusManager.getCurrentKeyboardFocusManager();
            manager.focusNextComponent();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtTratamiento = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtDiagnostico = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblReceta = new javax.swing.JTable();
        btAddRow = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblImagenes = new javax.swing.JTable();
        btAgregarImagen = new javax.swing.JButton();
        btQuitarImagen = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(800, 412));

        jLabel8.setText("Tratamiento *");

        txtTratamiento.setColumns(20);
        txtTratamiento.setRows(5);
        jScrollPane2.setViewportView(txtTratamiento);

        jLabel9.setText("Receta");

        jLabel7.setText("Diagnóstico *");

        tblReceta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null}
            },
            new String [] {
                "Nombre del medicamento", "Cantidad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblReceta.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tblRecetaFocusLost(evt);
            }
        });
        tblReceta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblRecetaMouseClicked(evt);
            }
        });
        tblReceta.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tblRecetaPropertyChange(evt);
            }
        });
        tblReceta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tblRecetaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tblRecetaKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(tblReceta);
        if (tblReceta.getColumnModel().getColumnCount() > 0) {
            tblReceta.getColumnModel().getColumn(0).setResizable(false);
            tblReceta.getColumnModel().getColumn(1).setResizable(false);
            tblReceta.getColumnModel().getColumn(1).setPreferredWidth(5);
        }

        btAddRow.setText("+");
        btAddRow.setFocusable(false);
        btAddRow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddRowActionPerformed(evt);
            }
        });

        jLabel1.setText("Imágenes");

        tblImagenes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Ruta"
            }
        ));
        jScrollPane3.setViewportView(tblImagenes);

        btAgregarImagen.setText("+");
        btAgregarImagen.setFocusable(false);
        btAgregarImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAgregarImagenActionPerformed(evt);
            }
        });

        btQuitarImagen.setText("-");
        btQuitarImagen.setFocusable(false);
        btQuitarImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btQuitarImagenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btQuitarImagen, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btAgregarImagen, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btAddRow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel8)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 679, Short.MAX_VALUE)
                            .addComponent(txtDiagnostico)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(30, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btAgregarImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btQuitarImagen))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtDiagnostico, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(38, 38, 38)
                        .addComponent(jLabel8)
                        .addGap(131, 131, 131)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btAddRow, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btAddRowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddRowActionPerformed
        // TODO add your handling code here:
        DefaultTableModel modelo = (DefaultTableModel) tblReceta.getModel();

        modelo.addRow(new Object[]{});

    }//GEN-LAST:event_btAddRowActionPerformed

    private void btAgregarImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAgregarImagenActionPerformed
        // TODO add your handling code here:
        DefaultTableModel modelo = (DefaultTableModel) tblImagenes.getModel();
        JFileChooser j = new JFileChooser();
        FileNameExtensionFilter fi = new FileNameExtensionFilter("imagenes y pdf", "pdf", "jpg", "jpeg", "png");
        j.setFileFilter(fi);
        int se = j.showOpenDialog(this);
        if (se == 0) {
            modelo.addRow(new Object[]{j.getSelectedFile().getName(), j.getSelectedFile().getAbsolutePath()});

        }
    }//GEN-LAST:event_btAgregarImagenActionPerformed

    private void btQuitarImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btQuitarImagenActionPerformed
        // TODO add your handling code here:

        if (tblImagenes.getSelectedRow() >= 0) {
            DefaultTableModel modelo = (DefaultTableModel) tblImagenes.getModel();
            modelo.removeRow(tblImagenes.getSelectedRow());

        }
    }//GEN-LAST:event_btQuitarImagenActionPerformed

    private void tblRecetaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblRecetaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tblRecetaKeyPressed

    private void tblRecetaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblRecetaKeyTyped
        // TODO add your handling code here:

        if (tblReceta.getSelectedColumn() == 1) {
            int key = evt.getKeyChar();

            boolean numeros = key >= 48 && key <= 57;

            if (!numeros) {
                evt.consume();
            }
        }

    }//GEN-LAST:event_tblRecetaKeyTyped

    private void tblRecetaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblRecetaMouseClicked
        // TODO add your handling code here:
        if (tblReceta.getSelectedColumn() == 1) {
            tblReceta.setValueAt("", tblReceta.getSelectedRow(), 1);
        }
    }//GEN-LAST:event_tblRecetaMouseClicked

    private void tblRecetaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tblRecetaFocusLost
        // TODO add your handling code here:
    
    }//GEN-LAST:event_tblRecetaFocusLost

    private void tblRecetaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tblRecetaPropertyChange
        // TODO add your handling code here:

    }//GEN-LAST:event_tblRecetaPropertyChange


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAddRow;
    private javax.swing.JButton btAgregarImagen;
    private javax.swing.JButton btQuitarImagen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    public static javax.swing.JTable tblImagenes;
    public static javax.swing.JTable tblReceta;
    public static javax.swing.JTextField txtDiagnostico;
    public static javax.swing.JTextArea txtTratamiento;
    // End of variables declaration//GEN-END:variables
}
